<form action="" method="post">

    <h4>Registration</h4>
    
    <div>   
        <label for="title">Title </label><br />
        <select name ="title"><br />
            <option value = "Mr"> Mr</option>
            <option value = "Mrs"> Mrs</option>
            <option value = "Ms"> Ms</option>
        </select>
        
    </div>

    <div>
        <label for="firstname">First Name </label><br />
        <input name="firstname" type="firstname"/>
    </div>

      <div>
       <label for="lastname">Last Name </label><br />
        <input name="lastname" type="lasttname"/>
    </div>
    
      <div>
        <label for="email">Email </label><br />
        <input name="email" type="email"/>
    </div>
    
    <div>
        <label for="confirmEmail">Confirm email </label><br />
        <input name="confirmEmail" type="confirmEmail"/>
    </div>
    
    <div>
        <label for="password">Password: </label><br />
        <input name="password" type="password"/>
    </div>
    
    <div>
        <label for="confirmPassword">Confirm Password </label><br />
        <input name="confirmPassword" type="password"/>
    </div>
    
       <button type="submit">Register</button>
</form>
